//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeapCSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-130")]
        public float rLeapMinX {
            get {
                return ((float)(this["rLeapMinX"]));
            }
            set {
                this["rLeapMinX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public float rLeapMaxX {
            get {
                return ((float)(this["rLeapMaxX"]));
            }
            set {
                this["rLeapMaxX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float rLeapMinY {
            get {
                return ((float)(this["rLeapMinY"]));
            }
            set {
                this["rLeapMinY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public float rLeapMaxY {
            get {
                return ((float)(this["rLeapMaxY"]));
            }
            set {
                this["rLeapMaxY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100")]
        public float rLeapMinZ {
            get {
                return ((float)(this["rLeapMinZ"]));
            }
            set {
                this["rLeapMinZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float rLeapMaxZ {
            get {
                return ((float)(this["rLeapMaxZ"]));
            }
            set {
                this["rLeapMaxZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int iLeapTrackPalm {
            get {
                return ((int)(this["iLeapTrackPalm"]));
            }
            set {
                this["iLeapTrackPalm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iLeapTrackThumb {
            get {
                return ((int)(this["iLeapTrackThumb"]));
            }
            set {
                this["iLeapTrackThumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iLeapTrackPointer {
            get {
                return ((int)(this["iLeapTrackPointer"]));
            }
            set {
                this["iLeapTrackPointer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iLeapTrackMiddle {
            get {
                return ((int)(this["iLeapTrackMiddle"]));
            }
            set {
                this["iLeapTrackMiddle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iLeapTrackFourth {
            get {
                return ((int)(this["iLeapTrackFourth"]));
            }
            set {
                this["iLeapTrackFourth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iLeapTrackPinky {
            get {
                return ((int)(this["iLeapTrackPinky"]));
            }
            set {
                this["iLeapTrackPinky"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int iSpeedSmoother {
            get {
                return ((int)(this["iSpeedSmoother"]));
            }
            set {
                this["iSpeedSmoother"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CurrentWorkingSpace {
            get {
                return ((int)(this["CurrentWorkingSpace"]));
            }
            set {
                this["CurrentWorkingSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int iMaxSpeed {
            get {
                return ((int)(this["iMaxSpeed"]));
            }
            set {
                this["iMaxSpeed"] = value;
            }
        }
    }
}
